# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine AS python-base

# Install system dependencies for Python and Node
RUN apk add --no-cache gcc musl-dev linux-headers nodejs npm

# --- MCP Python server (optional) ---
WORKDIR /mcp
COPY mcp /mcp
RUN if [ -f install.sh ]; then chmod +x install.sh && ./install.sh; fi

# --- MCP REST wrapper ---
WORKDIR /app
COPY app /app
RUN pip install --upgrade pip && pip install --no-cache-dir .

# --- Entrypoint and runtime flexibility ---
EXPOSE 8000

# Copy entrypoint script
WORKDIR /
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Allow mounting volumes for data/config (Kubernetes/Helm ready)
VOLUME ["/data", "/config"]

# Default: start REST API, but allow override for custom MCP server commands
ENTRYPOINT ["/start.sh"]
# Pass all arguments to entrypoint for maximum flexibility
CMD []
