# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim-bullseye

# Install system dependencies for Python and Node
RUN apt-get update && apt-get install -y \
    gcc \
    musl-dev \
    curl \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# --- MCP Python server (optional) ---
COPY mcp /mcp
WORKDIR /mcp
RUN if [ -f install.sh ]; then chmod +x install.sh && ./install.sh; fi
RUN if [ -f requirements.txt ]; then pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt; fi
RUN if [ -f pyproject.toml ]; then pip install --upgrade pip && pip install --no-cache-dir .; fi
# Install Node.js dependencies if package.json exists
RUN if [ -f package.json ]; then npm install; fi

# --- MCP REST wrapper ---
WORKDIR /app
COPY app /app
RUN pip install --upgrade pip && pip install --no-cache-dir .

# --- Entrypoint and runtime flexibility ---
EXPOSE 8000

# Copy entrypoint script
WORKDIR /
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Allow mounting volumes for data/config (Kubernetes/Helm ready)
VOLUME ["/data", "/config"]

# Default: start REST API, but allow override for custom MCP server commands
ENTRYPOINT ["/start.sh"]
# Pass all arguments to entrypoint for maximum flexibility
CMD []
