name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:

      - name: Verify CLA
        id: cla
        uses: contributor-assistant/github-action@v2.6.1
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          branch: main
          remote-organization-name: inxm-ai
          remote-repository-name: cla-signatures
          path-to-document: https://github.com/inxm-ai/mcp-rest-server/blob/main/CONTRIBUTING.md#-contributor-license-agreement-cla          
          allowlist: bot*